# Generated by Django 5.2.12 on 2026-03-18 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('approved_limit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('current_debt', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_loan_id', models.CharField(blank=True, max_length=100, null=True)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tenure', models.IntegerField(help_text='Tenure in months')),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest in percent', max_digits=5)),
                ('monthly_repayment', models.DecimalField(decimal_places=2, max_digits=14)),
                ('emis_paid_on_time', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='credit.customer')),
            ],
        ),
    ]
