# Generated by Django 5.2.12 on 2026-03-18 09:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('customers_created', models.IntegerField(default=0)),
                ('customers_updated', models.IntegerField(default=0)),
                ('customers_skipped', models.IntegerField(default=0)),
                ('loans_created', models.IntegerField(default=0)),
                ('loans_updated', models.IntegerField(default=0)),
                ('loans_skipped', models.IntegerField(default=0)),
                ('logs', models.TextField(blank=True, default='')),
            ],
        ),
    ]
